force-app/main/default/objects/Workforce_Management_Platform_Settings__c/Workforce_Management_Platform_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configure settings for the Workforce Management Platform API.</description>
    <label>Workforce Management Platform Settings</label>
</CustomObject>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The maximum number of records to be processed in a single transaction. Note current implementation is limited to 100.</description>
    <inlineHelpText>The maximum number of records to be processed in a single transaction. Note current implementation is limited to 100.</inlineHelpText>
    <label>Batch Size</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If unchecked, when the scheduler class is executed, no jobs will be queued.</description>
    <inlineHelpText>If unchecked, when the scheduler class is executed, no jobs will be queued.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>The maximum number of attempts which a Case record will be processed.</description>
    <inlineHelpText>The maximum number of attempts which a Case record will be processed.</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Max_Records__c.field-meta.xml
<CustomField>
    <fullName>Max_Records__c</fullName>
    <description>The maximum number of records to be picked up when the scheduled job runs.</description>
    <inlineHelpText>The maximum number of records to be picked up when the scheduled job runs.</inlineHelpText>
    <label>Max Records</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseCloseSchedulable.cls
/**
 * @description - Schedule the Batch Job to process closed Case records.
 */
global class CaseCloseSchedulable implements Schedulable {
  /**
   * @description - Implements the execute method of the Schedulable interface.
   *                This then starts the desired Batch Job to process the
   *                closed Case records.
   *
   * @param context - Context for the Scheduled Job, contains the Job Id
   */
  global void execute(SchedulableContext context) {
    // Get the Batch Job settings for the Workforce Management Platform
    Workforce_Management_Platform_Settings__c settings;
    settings = Workforce_Management_Platform_Settings__c.getOrgDefaults();
    Boolean enabled = settings.Enabled__c;
    Integer maxRecords = (Integer) settings.Max_Records__c;
    Integer batchSize = (Integer) settings.Batch_Size__c;
    Integer maxAttempts = (Integer) settings.Max_Attempts__c;

    // Check the Batch Job settings to see if it's enabled or disabled
    if (enabled == false) {
      System.debug(LoggingLevel.WARN, 'Job has been disabled');
      return;
    }

    // Create a new Batch Job
    CaseCloseBatch job = new CaseCloseBatch(maxRecords, maxAttempts);
    Id jobId = Database.executeBatch(job, batchSize);
    System.debug('Job Id: ' + jobId);
  }
}