force-app/main/default/objects/Workforce_Management_Platform_Settings__c/Workforce_Management_Platform_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configure settings for the Workforce Management Platform API.</description>
    <label>Workforce Management Platform Settings</label>
</CustomObject>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The maximum number of records to be processed in a single transaction. Note current implementation is limited to 100.</description>
    <inlineHelpText>The maximum number of records to be processed in a single transaction. Note current implementation is limited to 100.</inlineHelpText>
    <label>Batch Size</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If unchecked, when the scheduler class is executed, no jobs will be queued.</description>
    <inlineHelpText>If unchecked, when the scheduler class is executed, no jobs will be queued.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The URL of the API endpoint used to make callouts to the Workforce Management Platform.</description>
    <inlineHelpText>The URL of the API endpoint used to make callouts to the Workforce Management Platform.</inlineHelpText>
    <label>Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>The maximum number of attempts which a Case record will be processed.</description>
    <inlineHelpText>The maximum number of attempts which a Case record will be processed.</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Max_Records__c.field-meta.xml
<CustomField>
    <fullName>Max_Records__c</fullName>
    <description>The maximum number of records to be picked up when the scheduled job runs.</description>
    <inlineHelpText>The maximum number of records to be picked up when the scheduled job runs.</inlineHelpText>
    <label>Max Records</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <description>Email address to send job notifications to.</description>
    <inlineHelpText>Email address to send job notifications to.</inlineHelpText>
    <label>Notification Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The timeout in seconds for each API callout request.</description>
    <inlineHelpText>The timeout in seconds for each API callout request.</inlineHelpText>
    <label>Timeout</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseCloseSchedulableTest.cls
@isTest
private class CaseCloseSchedulableTest {
  // Dummy CRON expression
  static final String CRON_EXP = '0 0 * * * ?';
  /**
   * @description - Sets up initial test data which is re-used in multiple tests
   */
  @TestSetup
  static void makeData() {
    // Create Custom Setting record
    Workforce_Management_Platform_Settings__c settings = new Workforce_Management_Platform_Settings__c();
    settings.Enabled__c = true;
    settings.Endpoint__c = 'https://example.com';
    settings.Max_Attempts__c = 3;
    settings.Max_Records__c = 100;
    settings.Batch_Size__c = 10;
    settings.Notification_Email__c = 'test@test.invalid';
    settings.Timeout__c = 30;
    insert settings;
  }

  /**
   * @description - Tests the Schedulable class with the job being 'enabled'
   *                in the Custom Settings. Expect a Batch Job to be queued.
   */
  @IsTest
  static void testScheduledJobEnabled() {
    // Start test
    Test.startTest();

    // Schedule the job
    String jobId = System.schedule(
      'CaseCloseSchedulableTest',
      CRON_EXP,
      new CaseCloseSchedulable()
    );

    // Stop test
    Test.stopTest();

    // Verify results

    // Get the Apex Class for the Batch Job
    List<ApexClass> apexClass = [
      SELECT Id
      FROM ApexClass
      WHERE Name = :CaseCloseBatch.class.getName()
      LIMIT 1
    ];

    // Check if there are any queued job for the Apex Class
    Integer enqueuedJobs = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE
        JobType = 'BatchApex'
        AND Status IN ('Processing', 'Preparing', 'Queued')
        AND ApexClassId = :apexClass
    ];

    System.assertEquals(1, enqueuedJobs, 'Incorrect number of enqueuedJobs');
  }

  /**
   * @description - Tests the Schedulable class with the job being 'enabled'
   *                in the Custom Settings. Expect a Batch Job to be queued.
   */
  @IsTest
  static void testScheduledJobDisabled() {
    // Disable the job, so that no batches get executed
    Workforce_Management_Platform_Settings__c settings;
    settings = [
      SELECT Id, Enabled__c
      FROM Workforce_Management_Platform_Settings__c
      LIMIT 1
    ];
    settings.Enabled__c = false;
    update settings;

    // Start test
    Test.startTest();

    // Schedule the job
    String jobId = System.schedule(
      'CaseCloseSchedulableTest',
      CRON_EXP,
      new CaseCloseSchedulable()
    );

    // Stop test
    Test.stopTest();

    // Verify results

    // Get the Apex Class for the Batch Job
    List<ApexClass> apexClass = [
      SELECT Id
      FROM ApexClass
      WHERE Name = :CaseCloseBatch.class.getName()
      LIMIT 1
    ];

    // Check if there are any queued job for the Apex Class
    Integer enqueuedJobs = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE
        JobType = 'BatchApex'
        AND Status IN ('Processing', 'Preparing', 'Queued')
        AND ApexClassId = :apexClass
    ];

    System.assertEquals(0, enqueuedJobs, 'Incorrect number of enqueuedJobs');
  }
}