force-app/main/default/objects/Case/fields/Closed_By__c.field-meta.xml
<CustomField>
    <fullName>Closed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who closed this Case record.</description>
    <inlineHelpText>User who closed this Case record.</inlineHelpText>
    <label>Closed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Closed_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Integration_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Integration_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Integration Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Integration_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Job_Id__c</fullName>
    <description>Apex Job Id for the job executing.</description>
    <inlineHelpText>Apex Job Id for the job executing.</inlineHelpText>
    <label>Integration Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>TBC</description>
    <inlineHelpText>TBC</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/Workforce_Management_Platform_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configure settings for the Workforce Management Platform API.</description>
    <label>Workforce Management Platform Settings</label>
</CustomObject>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The maximum number of records to be processed in a single transaction. Note current implementation is limited to 100.</description>
    <inlineHelpText>The maximum number of records to be processed in a single transaction. Note current implementation is limited to 100.</inlineHelpText>
    <label>Batch Size</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If unchecked, when the scheduler class is executed, no jobs will be queued.</description>
    <inlineHelpText>If unchecked, when the scheduler class is executed, no jobs will be queued.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The URL of the API endpoint used to make callouts to the Workforce Management Platform.</description>
    <inlineHelpText>The URL of the API endpoint used to make callouts to the Workforce Management Platform.</inlineHelpText>
    <label>Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>The maximum number of attempts which a Case record will be processed.</description>
    <inlineHelpText>The maximum number of attempts which a Case record will be processed.</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Max_Records__c.field-meta.xml
<CustomField>
    <fullName>Max_Records__c</fullName>
    <description>The maximum number of records to be picked up when the scheduled job runs.</description>
    <inlineHelpText>The maximum number of records to be picked up when the scheduled job runs.</inlineHelpText>
    <label>Max Records</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <description>Email address to send job notifications to.</description>
    <inlineHelpText>Email address to send job notifications to.</inlineHelpText>
    <label>Notification Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The timeout in seconds for each API callout request.</description>
    <inlineHelpText>The timeout in seconds for each API callout request.</inlineHelpText>
    <label>Timeout</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseCloseBatchTest.cls
@IsTest
public with sharing class CaseCloseBatchTest {
  static final String STATUS_PROCESSING = CaseCloseBatch.STATUS_PROCESSING;
  static final String STATUS_COMPLETE = CaseCloseBatch.STATUS_COMPLETE;
  static final String STATUS_ERROR = CaseCloseBatch.STATUS_ERROR;

  /**
   * @description - Sets up initial test data which is re-used in multiple tests
   */
  @TestSetup
  static void makeData() {
    // Create basic test data
    List<Case> caseRecords;
    caseRecords = CaseTestDataFactory.createCaseRecords(100, 'Closed');

    // Make sure test data included required fields (in case Trigger does not fire)
    for (Case caseRecord : caseRecords) {
      caseRecord.Closed_By__c = UserInfo.getUserId();
    }

    // Insert test data
    insert caseRecords;

    // Create Custom Setting record
    Workforce_Management_Platform_Settings__c settings = new Workforce_Management_Platform_Settings__c();
    settings.Enabled__c = true;
    settings.Endpoint__c = 'https://example.com';
    settings.Max_Attempts__c = 3;
    settings.Max_Records__c = 100;
    settings.Batch_Size__c = 10;
    settings.Notification_Email__c = 'test@test.invalid';
    settings.Timeout__c = 30;
    insert settings;
  }

  /**
   * @description - Executes a positive test, making sure the batch query
   *                selected the correct records. Does not test execution
   *                results as they're based on a callout, which cannot be
   *                tested in this class.
   */
  @IsTest
  static void executeBatchTest() {
    Integer maxRecords = 100;
    Integer batchSize = 100;
    Integer maxAttempts = 3;

    // Start test
    Test.startTest();

    // Execute Batch Job
    CaseCloseBatch job = new CaseCloseBatch(maxRecords, maxAttempts);
    Id jobId = Database.executeBatch(job, batchSize);

    // Stop test
    Test.stopTest();

    // Verify results
    // Get updated Case records
    List<Case> newCaseRecords = [
      SELECT
        Id,
        Integration_Job_Id__c,
        Integration_Status__c,
        Integration_Attempts__c
      FROM Case
      WHERE Integration_Status__c != NULL
    ];

    // Make sure we have enough test data
    System.assertEquals(
      100,
      newCaseRecords.size(),
      'WRong number of test records'
    );

    // Check each record for expected data
    for (Case caseRecord : newCaseRecords) {
      String caseJobId = caseRecord.Integration_Job_Id__c;
      System.assertEquals(jobId, caseJobId, 'Incorrect Job Id');

      String status = caseRecord.Integration_Status__c;
      System.assertEquals(STATUS_PROCESSING, status, 'Incorrect Status');
    }
  }

  /**
   * @description - Executes a positive test, to make sure the email
   *                notification method is working.
   */
  @IsTest
  static void sendMaxAttemptsNotificationTest() {
    Id jobId = '7079D00000KuCCVQA3';
    String email = 'test@test.invalid';
    List<Case> caseRecords = [
      SELECT
        Id,
        Integration_Job_Id__c,
        Integration_Status__c,
        Integration_Attempts__c
      FROM Case
      LIMIT 100
    ];

    // Start test
    Test.startTest();

    // Execute method
    CaseCloseBatch.sendMaxAttemptsNotification(jobId, email, caseRecords);

    // Get the number of emails sent in this transaction
    Integer emailInvocations = Limits.getEmailInvocations();

    // Stop test
    Test.stopTest();

    // Verify results
    System.assertEquals(1, emailInvocations, 'Incorrect number of emails sent');
  }
}