force-app/main/default/objects/Case/fields/Closed_By__c.field-meta.xml
<CustomField>
    <fullName>Closed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who closed this Case record.</description>
    <inlineHelpText>User who closed this Case record.</inlineHelpText>
    <label>Closed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Closed_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Integration_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Integration_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Integration Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Integration_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Job_Id__c</fullName>
    <description>Apex Job Id for the job executing.</description>
    <inlineHelpText>Apex Job Id for the job executing.</inlineHelpText>
    <label>Integration Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>TBC</description>
    <inlineHelpText>TBC</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <description>TBC</description>
    <inlineHelpText>TBC</inlineHelpText>
    <label>Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/Workforce_Management_Platform_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configure settings for the Workforce Management Platform API.</description>
    <label>Workforce Management Platform Settings</label>
</CustomObject>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The URL of the API endpoint used to make callouts to the Workforce Management Platform.</description>
    <inlineHelpText>The URL of the API endpoint used to make callouts to the Workforce Management Platform.</inlineHelpText>
    <label>Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <description>Email address to send job notifications to.</description>
    <inlineHelpText>Email address to send job notifications to.</inlineHelpText>
    <label>Notification Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Workforce_Management_Platform_Settings__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The timeout in seconds for each API callout request.</description>
    <inlineHelpText>The timeout in seconds for each API callout request.</inlineHelpText>
    <label>Timeout</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseCloseBatch.cls
/**
 * @description - Batch Job to process closed Case records.
 */
public with sharing class CaseCloseBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
  // Constants
  public static final String CASE_STATUS_CLOSED = 'Closed';
  public static final String STATUS_PROCESSING = 'Processing';
  public static final String STATUS_COMPLETE = 'Complete';
  public static final String STATUS_ERROR = 'Error';
  @TestVisible
  static final String NOTIFICATION_EMAIL_SUBJECT = 'Case Close Integration Max Attempts Reached';
  @TestVisible
  static final String NOTIFICATION_EMAIL_BODY = 'These records have reached their Max Attempts limit:\n';

  Integer batchesProcessed = 0;
  Integer recordsProcessed = 0;
  Integer maxRecords;
  Integer maxAttempts;
  String endpoint;
  Integer timeout;
  String notificationEmail;

  public CaseCloseBatch(Integer maxRecords, Integer maxAttempts) {
    this.maxRecords = maxRecords;
    this.maxAttempts = maxAttempts;
  }

  /**
   * @description - Implements the start method of the Database.BatchableContext interface.
   *                This is executed when the Batch Job is started.
   *
   * @param bc - Context for the Batch Job, contains the Job Id
   */
  public Database.QueryLocator start(Database.BatchableContext bc) {
    System.debug('Starting batch job');
    Id jobId = bc.getJobId();

    // Get the API endpoint settings for the Workforce Management Platform
    Workforce_Management_Platform_Settings__c settings;
    settings = Workforce_Management_Platform_Settings__c.getOrgDefaults();
    this.timeout = (Integer) settings.Timeout__c;
    this.endpoint = settings.Endpoint__c;
    this.notificationEmail = settings.Notification_Email__c;

    // Define query to get records for batch jobs
    String q = 'SELECT Id, Closed_By__c, Integration_Attempts__c';
    q += ' FROM Case';
    q += ' WHERE Status = \'' + CASE_STATUS_CLOSED + '\'';
    q += ' AND Secret_Key__c = NULL';
    q += ' AND Integration_Status__c != \'' + STATUS_COMPLETE + '\'';
    q += ' AND (Integration_Status__c != \'' + STATUS_PROCESSING + '\'';
    q += ' OR Integration_Job_Id__c = \'' + jobId + '\')';
    q += ' AND Integration_Attempts__c < ' + this.maxAttempts;
    q += ' ORDER BY ClosedDate ASC';
    q += ' LIMIT ' + this.maxRecords;

    System.debug(q);

    // Update case records with Integration Status
    // This will avoid overlapping jobs if running concurrently
    List<Case> caseRecords = Database.query(q);
    for (Case caseRecord : caseRecords) {
      caseRecord.Integration_Job_Id__c = jobId;
      caseRecord.Integration_Status__c = STATUS_PROCESSING;
    }

    // Update records in Database
    update caseRecords;

    // Return QueryLocator for batch job
    return Database.getQueryLocator(q);
  }

  /**
   * @description - Implements the start method of the Database.BatchableContext interface.
   *                This is executed on each iteration of the Batch Job.
   *
   * @param bc - Context for the Batch Job, contains the Job Id
   * @param caseRecords - List of records to be processed in this batch
   */
  public void execute(Database.BatchableContext bc, List<Case> caseRecords) {
    // Increment batches and records processed counter
    this.batchesProcessed++;
    this.recordsProcessed = this.recordsProcessed + caseRecords.size();
    System.debug('Executing batch number ' + this.batchesProcessed);

    // Execute the business logic and API callout for these Case records
    // This will update records in the Database
    if (!Test.isRunningTest()) {
      // Only call if not running test, since contains callouts
      CaseCloseBatchHandler.execute(this.endpoint, this.timeout, caseRecords);
    }
  }

  /**
   * @description - Implements the finish method of the Database.BatchableContext interface.
   *                This is executed when the Batch Job is completed.
   *
   * @param bc - Context for the Batch Job, contains the Job Id
   */
  public void finish(Database.BatchableContext bc) {
    Id jobId = bc.getJobId();

    // Get all Case record from this Batch Job which have now reached their maximum attempts
    List<Case> caseRecords = [
      SELECT Id
      FROM Case
      WHERE
        Integration_Job_Id__c = :jobId
        AND Integration_Attempts__c >= :this.maxAttempts
    ];

    // If there are any records which reached their maximum attempts
    // Send an email to the email address configured in the settings
    if (!caseRecords.isEmpty()) {
      sendMaxAttemptsNotification(jobId, this.notificationEmail, caseRecords);
    }

    System.debug('Completed Job Id: ' + jobId);
  }

  @TestVisible
  static void sendMaxAttemptsNotification(
    Id jobId,
    String email,
    List<Case> caseRecords
  ) {
    // Get Case Record Ids from List of Cases
    List<Id> caseRecordIds = new List<Id>();
    for (Case caseRecord : caseRecords) {
      caseRecordIds.add(caseRecord.Id);
    }
    String serializedIds = JSON.serializePretty(caseRecordIds);

    // Prepare and send email
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    String[] toAddresses = new List<String>{ email };
    mail.setToAddresses(toAddresses);
    mail.setSubject(NOTIFICATION_EMAIL_SUBJECT + '- Job Id: ' + jobId);
    mail.setPlainTextBody(NOTIFICATION_EMAIL_BODY + serializedIds);
    Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
  }
}